src/main/java/com/woohaengshi/backend/BackendApplication.java, src/main/java/com/woohaengshi/backend/domain/Statistics.java, src/main/java/com/woohaengshi/backend/domain/StudyRecord.java, src/main/java/com/woohaengshi/backend/domain/Subject.java, src/main/java/com/woohaengshi/backend/domain/badge/Badge.java, src/main/java/com/woohaengshi/backend/domain/badge/Name.java, src/main/java/com/woohaengshi/backend/domain/member/Group.java, src/main/java/com/woohaengshi/backend/domain/member/Member.java, src/main/java/com/woohaengshi/backend/domain/member/State.java
- 개발시 필요한 domain들 추가
- closed #9 
nullable은 제가 임의로 생각해서 설정해놓았으니, 개발하시면서 필요에 따라 변경해서 사용해주세요 !
builder또한 마찬가지 입니다 생성자 위에 어노테이션 붙여서 사용하시면 될 것 같습니다.
=> [FEAT] 도메인 추가

build.gradle, src/main/java/com/woohaengshi/backend/config/SwaggerConfig.java, src/main/java/com/woohaengshi/backend/controller/SwaggerConfig.java
- Swagger 세팅
- closed #15
접속 URL: http://localhost:8080/swagger-ui/index.html
application.yml에 이거 추가해주세요
```
woohaengshi:
openapi:
dev-url: "http://localhost:8080"
prod-url: "https://api.myapp.com"
```
=> [feat/#15]: Swagger 세팅

build.gradle, src/main/resources/db/migration/V1__init.sql
- 데이터베이스 형상 관리를 위한 설정 및 init.sql 추가
- closed #12 
- 데이터베이스
기존에 있던 table들 drop하시고 application.yml을 아래와 같이 바꾼 후 실행해주세요 !
```
jpa:
hibernate:
ddl-auto: validate
flyway:
enabled: true
```
=> [DB] 데이터베이스 형상 관리 

.ebextensions-dev/00-makeFiles.config, .ebextensions-dev/01-set-timezone.config, .ebextensions-dev/02-https-redirect.config, .github/workflows/dev_deploy.yml, .platform/nginx.conf, Procfile, build.gradle, src/main/java/com/woohaengshi/backend/controller/RootController.java, src/main/resources/application-dev.yml
- dev 브랜치 적용전, 배포 테스트
- closed #27
단순 테스트
=> [CI] cicd 배포 테스트

.github/workflows/dev_deploy.yml
- 에러 나서 다시 테스트
- closed #27 
제발...
=> [CI] 배포 테스트

.github/workflows/dev_deploy.yml
- 배포 실패 해결하기..
- closed #27
제발.....해줘
=> [CI]: 버전 에러 의심

.github/workflows/format-check.yml, build.gradle
- 구글 포맷 해결하기
- closed #27 
제발류
=> [CI]: 구글 포맷 해결하기

src/main/java/com/woohaengshi/backend/controller/RootController.java
- 다시 배포
- closed #27
리뷰어들에게 하고 싶은 말
=> [CI]: 문제 해결 위해 다시 배포

src/main/java/com/woohaengshi/backend/controller/RootController.java
- 설명
- closed #이슈번호
- 동영상, 사진, 로그 등등
- ex) 큐알 성공 이미지, 스웨거, 포스트맨 등
리뷰어들에게 하고 싶은 말
=> [fix/#27]: 문제 해결 위해 다시 배포

src/main/java/com/woohaengshi/backend/controller/RootController.java
- 문제 해결 위해 다시 배포
- closed #27 
도메인 빼고 다되는데 안 됌. ㅜ
=> [FIX]: 문제 해결 위해 다시 배포

.github/workflows/dev_deploy.yml
- 다시 만든 ELB 적용
- closed #27 
ㅜㅜㅜ
=> [CI]: 다시 만든 ELB 적용

src/main/java/com/woohaengshi/backend/controller/RootController.java
- https으로 인해 한 번 더 배포
- closed #27
주소 변경될 듯 합니다
=> [CI]: https으로 인해 한 번 더 배포

src/main/java/com/woohaengshi/backend/controller/RootController.java
- ELB 환경변수 에러 해결
- closed #27
ㅜㅜㅜㅜㅜㅜㅜㅜ
=> [FIX]: ELB 환경변수 에러 해결

.github/workflows/dev_deploy.yml, .github/workflows/format-check.yml
- 구글 포맷 해결 test
- closed #27
구글 포맷 해결 도전
=> [FIX]: 구글 포맷 해결 test

.github/workflows/dev_deploy.yml
- 도전
- 설명
- closed #이슈번호
- 동영상, 사진, 로그 등등
- ex) 큐알 성공 이미지, 스웨거, 포스트맨 등
리뷰어들에게 하고 싶은 말
=> [fix/#27]: 구글 포맷 해결 tes

src/main/java/com/woohaengshi/backend/controller/StudyRecordController.java, src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowMonthlyRecordResponse.java, src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowMonthlyTotalResponse.java, src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowYearlyRecordResponse.java, src/main/java/com/woohaengshi/backend/dto/result/MonthlyTotalRecordResult.java, src/main/java/com/woohaengshi/backend/repository/StudyRecordRepository.java, src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordService.java, src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java, src/test/java/com/woohaengshi/backend/controller/StudyRecordControllerTest.java, src/test/java/com/woohaengshi/backend/repository/StudyRecordRepositoryTest.java, src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
- 캘린더를 연 별로 조회
- closed #48
- 포스트맨
jpql 사용하여 생성했습니다.
그리고 year 받을 때 1개밖에 없어서 그냥 int 로 받았습니다!
=> [FEAT] 캘린더 연 조회

src/main/java/com/woohaengshi/backend/controller/StudyRecordController.java
- study record controller 에서 오타 수정
- closed #55
죄송해용 🤯
=> [HOTFIX] study record controller 에서 오타 수정

src/main/java/com/woohaengshi/backend/domain/member/Course.java, src/main/java/com/woohaengshi/backend/dto/request/auth/SignInRequest.java, src/main/java/com/woohaengshi/backend/dto/request/auth/SignUpRequest.java, src/main/java/com/woohaengshi/backend/exception/ErrorCode.java, src/main/java/com/woohaengshi/backend/exception/ErrorResponse.java, src/main/java/com/woohaengshi/backend/exception/GlobalExceptionHandler.java, src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java, src/test/java/com/woohaengshi/backend/controller/auth/AuthControllerTest.java, src/test/java/com/woohaengshi/backend/service/auth/AuthServiceTest.java
- 회원 가입시 Course를 string으로 받도록 변경
- 405 에러 핸들링
- closed #60
=> [FEAT] 회원 가입시 Course를 string으로 받도록 변경

src/main/java/com/woohaengshi/backend/controller/StudyRecordController.java, src/test/java/com/woohaengshi/backend/controller/StudyRecordControllerTest.java, src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
- 회원 인증/인가 병합하여 타이머 및 캘린더 조회 수정
- closed #59 
전체적으로 수정이 필요한 부분 수정했습니다.
=> [FIX] 회원 인증/인가 병합하여 타이머 및 캘린더 조회 수정

src/main/java/com/woohaengshi/backend/controller/StudyRecordController.java
- @RequestParam = false 대신 defaultValue 사용으로 변경
- closed #59
=> [FIX] 캘린더 월 조회 api 수정

src/main/resources/application-dev.yml
=> [CI]: 배포용 application 코드 수정

src/main/java/com/woohaengshi/backend/config/AuthConfig.java, src/main/java/com/woohaengshi/backend/controller/RootController.java
- health check 경로 배포에 필수적이기 때문에
=> [CI]: health check 경로

src/main/java/com/woohaengshi/backend/repository/StatisticsRepository.java, src/main/java/com/woohaengshi/backend/repository/StatisticsSpecification.java, src/main/java/com/woohaengshi/backend/repository/StudyRecordRepository.java, src/main/java/com/woohaengshi/backend/repository/StudyRecordSpecification.java, src/main/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImpl.java
- repository에 있는 코드를 Specification만 사용하는 클래스를 정의하여 분리
- StatisticsServiceImpl에서 새로운 메소드를 정의하여 가독성을 높임
- closed #8
리뷰어들에게 하고 싶은 말
=> [REFACTOR]: Statistics 코드 리팩토링

src/main/resources/application-dev.yml
- yml s3 설정 추가
- closed #75
리뷰어들에게 하고 싶은 말
=> [CI]: yml s3 설정 추가

src/main/java/com/woohaengshi/backend/controller/MemberController.java, src/main/java/com/woohaengshi/backend/domain/member/Member.java, src/main/java/com/woohaengshi/backend/dto/request/member/ChangePasswordRequest.java, src/main/java/com/woohaengshi/backend/exception/ErrorCode.java, src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java, src/main/java/com/woohaengshi/backend/service/member/MemberService.java, src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java, src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java, src/test/java/com/woohaengshi/backend/controller/MemberControllerTest.java, src/test/java/com/woohaengshi/backend/service/member/MemberServiceTest.java, src/test/java/com/woohaengshi/backend/support/fixture/MemberFixture.java
=> [FEAT] 비밀번호 변경 기능

src/main/java/com/woohaengshi/backend/controller/MemberController.java, src/main/java/com/woohaengshi/backend/controller/auth/AuthController.java, src/main/java/com/woohaengshi/backend/controller/auth/CookieProvider.java, src/main/java/com/woohaengshi/backend/domain/member/Member.java, src/main/java/com/woohaengshi/backend/dto/result/SignInResult.java, src/main/java/com/woohaengshi/backend/exception/ErrorCode.java, src/main/java/com/woohaengshi/backend/service/auth/AuthService.java, src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java, src/main/java/com/woohaengshi/backend/service/member/MemberService.java, src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java, src/test/java/com/woohaengshi/backend/controller/MemberControllerTest.java, src/test/java/com/woohaengshi/backend/controller/auth/AuthControllerTest.java, src/test/java/com/woohaengshi/backend/service/auth/AuthServiceTest.java, src/test/java/com/woohaengshi/backend/service/member/MemberServiceTest.java
=> [FEAT] 회원 탈퇴 기능

src/main/java/com/woohaengshi/backend/config/WebConfig.java, src/main/java/com/woohaengshi/backend/controller/RootController.java
- 프론트엔드 배포 주소 추가
- closed #95
머지하면 바로 배포할게요!
=> [FEAT] 프론트엔드 배포 주소 추가

src/main/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImpl.java
=> [fix]: 랭킹 주간 버그 수정

src/main/resources/application-dev.yml
=> [fix]: 엑세스 토큰 시간 증가

src/main/java/com/woohaengshi/backend/service/statistics/StatisticsScheduler.java, src/main/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImpl.java
- 시간 버그 로직 추가
- 00시 ~ 5시 이전에는 전날 시간 보여줘야 함
- 주간/월간 초기화 코드 적용
죄송합니다ㅓ...
=> [FIX] 시간 버그 로직 추가

src/main/java/com/woohaengshi/backend/domain/member/Member.java, src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java, src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java, src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java
=> [FEAT] 회원 탈퇴 검증 기능 추가

.github/workflows/dev_deploy.yml, src/main/resources/application-dev.yml
- Redis 및 application.yml 수정
- closed #122
=> [CI] Redis 및 application.yml 수정

.ebextensions-dev/03-redis.config
=> [CI]: redis 설정 파일삭제

.ebextensions-dev/03-redis.config
=> [CI] redis 설정
